# **üìä Explora√ß√£o de Po√ßos no Brasil: Evolu√ß√£o ao Longo dos Anos** </br>
Autor: Paulo Roberto <br>
Data: Mar√ßo de 2025

üìù Este projeto combina o uso da biblioteca ``Bar Chart Race`` , que gera gr√°ficos de corridas de barras animados, com dados p√∫blicos sobre po√ßos perfurados nas bacias sedimentares brasileiras desde o in√≠cio das atividades explorat√≥rias no pa√≠s. Atrav√©s dessa visualiza√ß√£o din√¢mica e interativa, √© poss√≠vel compreender de forma intuitiva quais bacias receberam maior aten√ß√£o ao longo dos anos, destacando aquelas que se consolidaram como as mais exploradas e que est√£o associadas √†s maiores reservas de √≥leo e g√°s.

Importanto bibliotecas e lendo o arquivo baixado no site da ANP:

In [1]:
import pandas as pd
import bar_chart_race as bcr
import matplotlib.pyplot as plt
from IPython.display import HTML

In [2]:
df_pocos = pd.read_csv('Tabela_pocos_2025_Mar√ßo_16.csv', sep=';', encoding='latin1')

No arquivo original, foi adicionada uma coluna com o n√∫mero de po√ßos por linha, para que sejam contabilizados por ano e por bacia posteriormente. </br>
Foram utilizados todos os po√ßos, sem filtragem de classifica√ß√£o, mas isso poderia ter sido feito a depender da motiva√ß√£o do estudo.

In [3]:
df_pocos.head

<bound method NDFrame.head of                 POCO      CADASTRO           OPERADOR   POCO_OPERADOR ESTADO  \
0          1-AA-1-RN  721000712200                NaN   1AA  0001  RN     RN
1        1-ABV-1D-RN  721000514700  Potiguar E&P S.A.   1ABV 0001D RN     RN
2         1-AB-1A-SE  901200015200                NaN   1AB  0001A SE     SE
3          1-AB-1-BA  202200153900                NaN   1AB  0001  BA     BA
4          1-AB-1-PA  600300063100                NaN   1AB  0001  PA     PA
...              ...           ...                ...             ...    ...
30946  9-VM-74PA-RJS  742810223800     Perenco Brasil  9VM  0074PARJS     RJ
30947  9-VM-75DP-RJS  742810224300     Perenco Brasil  9VM  0075DPRJS     RJ
30948  9-VM-76DP-RJS  742810226300     Perenco Brasil  9VM  0076DPRJS     RJ
30949      9-VQ-1-RN  721000902500                NaN   9VQ  0001  RN     RN
30950   9-XRL-1D-RJS   74281027414   TotalEnergies EP    9-XRL-1D-RJS     RJ

                BACIA     BLOCO SIG_CAMPO     CAMPO TERRA_MAR  ...  \
0            Potiguar    Brasil       NaN       NaN         T  ...
1            Potiguar  BT-POT-9     PAT    PATATIVA         T  ...
2             Sergipe    Brasil       NaN       NaN         T  ...
3      Tucano Central    Brasil       NaN       NaN         T  ...
4            Amazonas    Brasil       NaN       NaN         T  ...
...               ...       ...       ...       ...       ...  ...
30946          Campos        VM     VM     VERMELHO         M  ...
30947          Campos        VM     VM     VERMELHO         M  ...
30948          Campos        VM     VM     VERMELHO         M  ...
30949        Potiguar    Brasil       NaN       NaN         T  ...
30950          Campos      BC-2     XRL    XERELETE         M  ...

      DADOS_DIRECIONAIS  TESTE_A_CABO TESTE_DE_FORMACAO CANHONEIO TESTEMUNHO  \
0                   NaN           NaN               NaN       NaN        NaN
1                   NaN           NaN               NaN       NaN        NaN
2                   NaN           NaN               NaN       NaN        NaN
3                   NaN           NaN               NaN       NaN        NaN
4                   NaN           NaN               NaN       NaN        NaN
...                 ...           ...               ...       ...        ...
30946               NaN           NaN               NaN       NaN        NaN
30947               NaN           NaN               NaN       NaN        NaN
30948               NaN           NaN               NaN       NaN        NaN
30949               NaN           NaN               NaN       NaN        NaN
30950            Existe        Existe               NaN       NaN        NaN

      GEOQUIMICA                       SIG_SONDA               NOM_SONDA  \
0         Existe  CC-1                                               NaN
1         Existe                          SC-110  SONDA CONVENCIONAL 110
2         Existe                           SC-61   SONDA CONVENCIONAL 61
3         Existe                           SC-53   SONDA CONVENCIONAL 53
4         Existe  SM-1                                               NaN
...          ...                             ...                     ...
30946        NaN  SPM20                                              NaN
30947        NaN                           SPM19                SONDA 21
30948        NaN  SPM20                                              NaN
30949        NaN  PERC                                               NaN
30950        NaN                           NS-32              NORBE VIII

      ATINGIU_PRESAL DHA_ATUALIZACAO
0                NaN       16/3/2025
1                NaN       16/3/2025
2                NaN       16/3/2025
3                NaN       16/3/2025
4                NaN       16/3/2025
...              ...             ...
30946            NaN       16/3/2025
30947            NaN       16/3/2025
30948            NaN       16/3/2025
30949            NaN       16/3/2025
30950              N       16/3/2025

[30951 rows x 60 columns]>

In [4]:
df_pocos.head()

,POCO,CADASTRO,OPERADOR,POCO_OPERADOR,ESTADO,BACIA,BLOCO,SIG_CAMPO,CAMPO,TERRA_MAR,...,DADOS_DIRECIONAIS,TESTE_A_CABO,TESTE_DE_FORMACAO,CANHONEIO,TESTEMUNHO,GEOQUIMICA,SIG_SONDA,NOM_SONDA,ATINGIU_PRESAL,DHA_ATUALIZACAO
0,1-AA-1-RN,721000712200,NaN,1AA 0001 RN,RN,Potiguar,Brasil,NaN,NaN,T,...,NaN,NaN,NaN,NaN,NaN,Existe,CC-1,NaN,NaN,16/3/2025
1,1-ABV-1D-RN,721000514700,Potiguar E&P S.A.,1ABV 0001D RN,RN,Potiguar,BT-POT-9,PAT,PATATIVA,T,...,NaN,NaN,NaN,NaN,NaN,Existe,SC-110,SONDA CONVENCIONAL 110,NaN,16/3/2025
2,1-AB-1A-SE,901200015200,NaN,1AB 0001A SE,SE,Sergipe,Brasil,NaN,NaN,T,...,NaN,NaN,NaN,NaN,NaN,Existe,SC-61,SONDA CONVENCIONAL 61,NaN,16/3/2025
3,1-AB-1-BA,202200153900,NaN,1AB 0001 BA,BA,Tucano Central,Brasil,NaN,NaN,T,...,NaN,NaN,NaN,NaN,NaN,Existe,SC-53,SONDA CONVENCIONAL 53,NaN,16/3/2025
4,1-AB-1-PA,600300063100,NaN,1AB 0001 PA,PA,Amazonas,Brasil,NaN,NaN,T,...,NaN,NaN,NaN,NaN,NaN,Existe,SM-1,NaN,NaN,16/3/2025

In [5]:
# Certifique-se de que a coluna 'CONCLUSAO' √© do tipo datetime
df_pocos['CONCLUSAO'] = pd.to_datetime(df_pocos['CONCLUSAO'])

C:\Users\Paulo Roberto\AppData\Local\Temp\ipykernel_2788\229083518.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_pocos['CONCLUSAO'] = pd.to_datetime(df_pocos['CONCLUSAO'])

In [6]:
# Agrupe por 'BACIA' e pelo ano de 'CONCLUSAO', e conte o n√∫mero de po√ßos
df_pocos_bcr = df_pocos.groupby(['BACIA', df_pocos['CONCLUSAO'].dt.year]).size().reset_index(name='NUMERO_POCOS')

In [7]:
# Pivotar o DataFrame para ter os anos como colunas
df_pocos_bcr = df_pocos_bcr.pivot(index='BACIA', columns='CONCLUSAO', values='NUMERO_POCOS')

In [8]:
# Transpor o DataFrame para ter os anos como √≠ndice
df_pocos_bcr = df_pocos_bcr.T

In [9]:
# Resetar o √≠ndice para que os anos sejam uma coluna
df_pocos_bcr = df_pocos_bcr.reset_index()

In [10]:
# Exibir o DataFrame resultante
print(df_pocos_bcr)

BACIA  CONCLUSAO  Acre  Alagoas  Almada  Amazonas  Araripe  Barreirinhas  \
0         1922.0   NaN      NaN     NaN       NaN      NaN           NaN
1         1925.0   NaN      NaN     NaN       NaN      NaN           NaN
2         1937.0   NaN      NaN     NaN       NaN      NaN           NaN
3         1938.0   NaN      NaN     NaN       NaN      NaN           NaN
4         1939.0   NaN      NaN     NaN       NaN      NaN           NaN
..           ...   ...      ...     ...       ...      ...           ...
86        2021.0   NaN      NaN     NaN       2.0      NaN           NaN
87        2022.0   NaN      NaN     NaN       5.0      NaN           NaN
88        2023.0   NaN      NaN     NaN      11.0      NaN           NaN
89        2024.0   NaN      3.0     NaN       NaN      NaN           NaN
90        2025.0   NaN      NaN     NaN       NaN      NaN           NaN

BACIA  Bragan√ßa - Vizeu  Camamu  Campos  ...  Rio do Peixe  Santos  Sergipe  \
0                   NaN     1.0     NaN  ...           NaN     NaN      NaN
1                   NaN     1.0     NaN  ...           NaN     NaN      NaN
2                   NaN     NaN     NaN  ...           NaN     NaN      NaN
3                   NaN     NaN     NaN  ...           NaN     NaN      NaN
4                   NaN     NaN     NaN  ...           NaN     NaN      NaN
..                  ...     ...     ...  ...           ...     ...      ...
86                  NaN     NaN    24.0  ...           NaN    29.0      NaN
87                  NaN     NaN    36.0  ...           NaN    26.0      1.0
88                  NaN     NaN    42.0  ...           NaN    41.0      6.0
89                  NaN     NaN    37.0  ...           NaN    38.0     80.0
90                  NaN     NaN     1.0  ...           NaN     6.0      NaN

BACIA  Solim√µes  S√£o Francisco  S√£o Lu√≠s  Tacutu  Tucano Central  \
0           NaN            NaN       NaN     NaN             NaN
1           NaN            NaN       NaN     NaN             NaN
2           NaN            NaN       NaN     NaN             NaN
3           NaN            NaN       NaN     NaN             NaN
4           NaN            NaN       NaN     NaN             NaN
..          ...            ...       ...     ...             ...
86          NaN            NaN       NaN     NaN             NaN
87          NaN            NaN       NaN     NaN             NaN
88          NaN            NaN       NaN     NaN             NaN
89          NaN            NaN       NaN     NaN             NaN
90          NaN            NaN       NaN     NaN             NaN

BACIA  Tucano Norte  Tucano Sul
0               NaN         NaN
1               NaN         NaN
2               NaN         NaN
3               NaN         NaN
4               NaN         NaN
..              ...         ...
86              NaN         NaN
87              NaN         NaN
88              NaN         NaN
89              NaN         NaN
90              NaN         NaN

[91 rows x 38 columns]

In [11]:
df_pocos_bcr

BACIA,CONCLUSAO,Acre,Alagoas,Almada,Amazonas,Araripe,Barreirinhas,Bragan√ßa - Vizeu,Camamu,Campos,...,Rio do Peixe,Santos,Sergipe,Solim√µes,S√£o Francisco,S√£o Lu√≠s,Tacutu,Tucano Central,Tucano Norte,Tucano Sul
0,1922.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1925.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1937.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1938.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1939.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,2021.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,24.0,...,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2022.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,36.0,...,NaN,26.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2023.0,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,42.0,...,NaN,41.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2024.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,37.0,...,NaN,38.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Substituir NaN por 0
df_pocos_bcr.fillna(0, inplace=True)

In [13]:
df_pocos_bcr

BACIA,CONCLUSAO,Acre,Alagoas,Almada,Amazonas,Araripe,Barreirinhas,Bragan√ßa - Vizeu,Camamu,Campos,...,Rio do Peixe,Santos,Sergipe,Solim√µes,S√£o Francisco,S√£o Lu√≠s,Tacutu,Tucano Central,Tucano Norte,Tucano Sul
0,1922.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1925.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1937.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1938.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1939.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,2021.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,24.0,...,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,2022.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,36.0,...,0.0,26.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88,2023.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,42.0,...,0.0,41.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
89,2024.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,...,0.0,38.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,2025.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Certifique-se de que a coluna 'Ano' √© do tipo inteiro ou string
df_pocos_bcr['CONCLUSAO'] = df_pocos_bcr['CONCLUSAO'].astype(int)  # ou .astype(str)

In [15]:
# Definir a coluna 'CONCLUSAO' como √≠ndice
df_pocos_bcr.set_index('CONCLUSAO', inplace=True)

In [16]:
df_pocos_bcr

BACIA,Acre,Alagoas,Almada,Amazonas,Araripe,Barreirinhas,Bragan√ßa - Vizeu,Camamu,Campos,Cear√°,...,Rio do Peixe,Santos,Sergipe,Solim√µes,S√£o Francisco,S√£o Lu√≠s,Tacutu,Tucano Central,Tucano Norte,Tucano Sul
CONCLUSAO,,,,,,,,,,,,,,,,,,,,,
1922,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1925,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1937,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,24.0,0.0,...,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,36.0,0.0,...,0.0,26.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,42.0,0.0,...,0.0,41.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,0.0,...,0.0,38.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Criando um dataframe com ocorr√™ncias de po√ßos por bacia, agrupando-os por ano:

Esses s√£o os par√¢metros escolhidos para a visualiza√ß√£o, limitados pelas 10 maiores ocorr√™ncias por bacia por ano a fim de gerar uma melhor visualiza√ß√£o:

In [17]:
bcr.bar_chart_race(
    df_pocos_bcr,
    bar_label_size=7,
    tick_label_size=7,
    fixed_max=True,
    figsize=(5, 3),
    n_bars=10,
    title='Po√ßos Perfurados em cada Bacia por Ano',
    filename='pocos.html'
)

c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:889: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_values.iloc[:, 0] = df_values.iloc[:, 0].fillna(method='ffill')
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_yticklabels(self.df_values.columns)
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:226: UserWarning: Some of your columns never make an appearance in the animation. To reduce color repetition, set `filter_column_colors` to `True`
  warnings.warn("Some of your columns never make an appearance in the animation. "

In [18]:
# Exibir o HTML no notebook
HTML(filename='pocos.html')

Salvando o arquivo no formato gif:

In [19]:
bcr.bar_chart_race(df_pocos_bcr,
                   filename='pocos.gif',
                   bar_label_size=7, tick_label_size=7,
                   fixed_max=True,figsize=(5,3), n_bars=10,
                   title='Po√ßos Perfurados em cada Bacia por Ano')

c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:889: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_values.iloc[:, 0] = df_values.iloc[:, 0].fillna(method='ffill')
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_yticklabels(self.df_values.columns)
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))
c:\Users\Paulo Roberto\Downloads\myenv312\Lib\site-packages\bar_chart_race\_make_chart.py:226: UserWarning: Some of your columns never make an appearance in the animation. To reduce color repetition, set `filter_column_colors` to `True`
  warnings.warn("Some of your columns never make an appearance in the animation. "
MovieWriter imagemagick unavailable; using Pillow instead.

Dentre os insights percebidos, temos:

- O in√≠cio da explora√ß√£o se deu em terra, com as bacias de Rec√¥ncavo, Sergipe-Alagoas e Potiguar;
- A explora√ß√£o em mar come√ßou a partir da d√©cada de 50, e o protagonismo da Bacia de Campos come√ßa na d√©cada de 70;
- As bacias de Rec√¥ncavo, Sergipe-Alagoas, Potiguar e Esp√≠rito Santo continuam com alta produ√ß√£o ao longo dos anos, o que configura um cen√°rio muito positivo para movimenta√ß√£o de economias regionais em bacias maduras;
- H√° um destaque para a Bacia de Santos mais expressivo nos √∫ltimos anos por ser a maior bacia produtora atualmente.

Bibliografia



*   https://www.dexplo.org/bar_chart_race/
*   https://www.gov.br/anp/pt-br/assuntos/exploracao-e-producao-de-oleo-e-gas/dados-tecnicos/acervo-de-dados